networks:
  codinviec-backend:
    driver: bridge

volumes:
  codinviec-mysql-data:
  codinviec-redis-data:
  codinviec-kafka-data:
  portainer_data:

services:
  mysql:
    image: mysql:8.0
    container_name: codinviec-db
    environment:
      MYSQL_ROOT_PASSWORD: Codinviec123@
      MYSQL_DATABASE: codinviec_db
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "3306:3306"
    volumes:
      - codinviec-mysql-data:/var/lib/mysql
    networks:
      - codinviec-backend
    restart: unless-stopped

  redis:
    image: redis/redis-stack:7.2.0-v20
    container_name: codinviec-redis
    environment:
      REDIS_ARGS: "--requirepass Codinviec123@"
      REDISSTACK_ENABLE_INSIGHT: "yes"
      REDISSTACK_UI_BIND_ADDRESS: "0.0.0.0"
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - codinviec-redis-data:/data
    networks:
      - codinviec-backend
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    hostname: kafka
    container_name: kafka
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM6Qk"
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G"
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    volumes:
      - codinviec-kafka-data:/var/lib/kafka/data
    networks:
      - codinviec-backend
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-corporate
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8085:8080"
    networks:
      - codinviec-backend
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codinviec-app
    env_file:
      - .env
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/uploads/images:/uploads/images
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      - codinviec-backend
    restart: unless-stopped
