spring:
  application:
    name: it_job

  datasource:
    url: ${DB_URL}
    username: ${DB_ROOT}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_ACCESS_EXPIRED}
    refresh: ${JWT_REFRESH_EXPIRED}

upload:
  image: ${PATHIMAGE}

client:
  url: ${HOST}

redis:
  host: ${REDIS_HOST}
  password: ${REDIS_PASSWORD}
  port: ${REDIS_PORT}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha


logging:
  level:
    root: INFO
    com.project.it_job: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/it_job.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
