spring:
  application:
    name: it_job
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOSTRAP_SERVER}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google" #đường dẫn này phải khớp với khai báo trong gg cloud nó là được dẫn gg gọi ngược lại BE
            scope:
              - email
              - profile

        provider:
          google: # mình sẽ security bên google
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

ggurl:
  redirect-url:  /login/oauth2/code/google
  login-url: /oauth2/authorization/google


jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_ACCESS_EXPIRED}
    refresh: ${JWT_REFRESH_EXPIRED}

upload:
  image: ${UPLOAD_IMAGE}

url:
  client: ${URL_CLIENT}
  server: ${URL_SERVER}

redis:
  host: ${REDIS_HOST}
  password: ${REDIS_PASSWORD}
  port: ${REDIS_PORT}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    root: INFO
    com.project.it_job: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/it_job.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
