spring:
  application:
    name: it_job
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOSTRAP_SERVER}

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_ACCESS_EXPIRED}
    refresh: ${JWT_REFRESH_EXPIRED}

upload:
  image: ${UPLOAD_IMAGE}

client:
  url: ${CLIENT_URL}

redis:
  host: ${REDIS_HOST}
  password: ${REDIS_PASSWORD}
  port: ${REDIS_PORT}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    root: INFO
    com.project.it_job: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/it_job.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
