spring:
  application:
    name: codinviec
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/codinviec_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Codinviec123@}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  kafka:
    bootstrap-servers: ${KAFKA_BOOSTRAP_SERVER:localhost9094}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_GOOGLE_CLIENT_ID:253105273512-o9u9tqfjt7tqaq4cp3qln0pagoc9gjf6.apps.googleusercontent.com}
            client-secret: ${SPRING_SECURITY_GOOGLE_CLIENT_SECRET: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}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
server:
  port: ${PORT:${SERVER_PORT:8080}}

jwt:
  secret: ${JWT_SECRET:pgib14v/ChCexRgVz8vtPSds9VUOeyXm3KGekziH5Ys=}
  expiration:
    access: ${JWT_ACCESS_EXPIRED:900000} #15m
    refresh: ${JWT_REFRESH_EXPIRED:604800000000} #7d

upload:
  image: ${UPLOAD_IMAGE:D:\}

client:
  url: ${CLIENT_URL:http://localhost:3000}

redis:
  host: ${REDIS_HOST:localhost}
  password: ${REDIS_PASSWORD:Codinviec123@}
  port: ${REDIS_PORT:6379}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

vnpay:
  tmn-code: ${VNP_TMNCODE}
  hash-secret: ${VNP_HASHSECRET}
  pay-url: ${VNP_URL}
  return-url: ${VNP_RETURN_URL}


logging:
  level:
    root: INFO
    com.project.it_job: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/it_job.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
