name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout source code
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # 2Ô∏è‚É£ Upload code to VPS
      - name: Upload Project to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: ${{ secrets.DEPLOY_PATH }}

      # 3Ô∏è‚É£ Build & Deploy ONLY Spring Boot service
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}

            echo "üì¶ Building new JAR..."
            mvn clean package -DskipTests

             echo "üê≥ Rebuilding Docker images..."
            docker compose build

            echo "üîÑ Starting ALL services..."
            docker compose up -d

            echo "üßπ Removing unused images..."
            docker image prune -f

            echo "üéâ Backend Deployment Completed Successfully!"
